CUDA_VISIBLE_DEVICES=0 python train.py \
--gpus 1 \
--model_order 32 \
--max_train_order 32 \
--batch_size 128 \
--num_workers 8 \
--lr 1e-5 \
--gradient_clip_val 0.9 \
--gradient_clip_algorithm norm \
--hidden_dim 2048 \
--shuffle \
--filter_method all \
--max_epochs 2000 \
--save_ckpt_every_n_epochs 100 \
--num_train_examples 8333 \
--experiment_name duration
